create database HumanResource
go
use HumanResource
go
CREATE SCHEMA HR
GO

CREATE TABLE HR.REGIONS 
    ( 
     REGION_ID FLOAT  NOT NULL , 
     REGION_NAME VARCHAR (25) 
    ) 
;

ALTER TABLE HR.REGIONS   ADD CONSTRAINT REG_ID_PK PRIMARY KEY ( REGION_ID ) ;


CREATE TABLE HR.COUNTRIES 
    ( 
     COUNTRY_ID CHAR (2)  NOT NULL , --!identity 
     COUNTRY_NAME VARCHAR (40) , 
     REGION_ID FLOAT ,
    ) 
;

ALTER TABLE HR.COUNTRIES  ADD CONSTRAINT COUNTRY_C_ID_PK PRIMARY KEY (COUNTRY_ID);

CREATE TABLE HR.DEPARTMENTS 
    ( 
     DEPARTMENT_ID SMALLINT  NOT NULL , --!identity 
     DEPARTMENT_NAME VARCHAR (30)  NOT NULL , 
     MANAGER_ID INT  , 
     LOCATION_ID SMALLINT --!identity 
    ) 
;


ALTER TABLE HR.DEPARTMENTS ADD CONSTRAINT DEPT_ID_PK PRIMARY KEY ( DEPARTMENT_ID ) ;


CREATE TABLE HR.EMPLOYEES 
    ( 
     EMPLOYEE_ID INT   NOT NULL , --!identity 
     FIRST_NAME VARCHAR (20) , --!identity 
     LAST_NAME VARCHAR (25)  NOT NULL , --!identity 
     EMAIL VARCHAR (25)  NOT NULL , 
     PHONE_NUMBER VARCHAR (20) , 
     HIRE_DATE DATETIME  NOT NULL , 
     JOB_ID VARCHAR (10)   NOT NULL , --!identity 
     SALARY DECIMAL (8,2) , 
     COMMISSION_PCT DECIMAL (2,2) , 
     MANAGER_ID INT , --!identity 
     DEPARTMENT_ID SMALLINT   --!identity 
    ) 
;

ALTER TABLE HR.EMPLOYEES 
    ADD CONSTRAINT EMP_SALARY_MIN 
    CHECK ( salary > 0) 
;


-----! creacion de indice
ALTER TABLE HR.EMPLOYEES 
    ADD CONSTRAINT EMP_EMP_ID_PK PRIMARY KEY ( EMPLOYEE_ID ) ;

ALTER TABLE HR.EMPLOYEES 
    ADD CONSTRAINT EMP_EMAIL_UK UNIQUE ( EMAIL ) ;


CREATE TABLE HR.JOBS 
    ( 
     JOB_ID VARCHAR (10)  NOT NULL , --!identity 
     JOB_TITLE VARCHAR (35)  NOT NULL , 
     MIN_SALARY INT  , 
     MAX_SALARY INT  
    ) 
;

ALTER TABLE HR.JOBS ADD CONSTRAINT JOB_ID_PK PRIMARY KEY ( JOB_ID ) ;


CREATE TABLE HR.JOB_HISTORY 
    ( 
     EMPLOYEE_ID INT   NOT NULL , --!identity 
     START_DATE DATETIME  NOT NULL , --!identity 
     END_DATE DATETIME  NOT NULL , 
     JOB_ID VARCHAR (10)  NOT NULL ,  --!identity 
     DEPARTMENT_ID SMALLINT  --!identity 
    ) 
;
ALTER TABLE HR.JOB_HISTORY  ADD CONSTRAINT JHIST_ID_DATE_PK PRIMARY KEY ( EMPLOYEE_ID, START_DATE ) ;

CREATE TABLE HR.LOCATIONS 
    ( 
     LOCATION_ID SMALLINT   NOT NULL , --!identity 
     STREET_ADDRESS VARCHAR (40) , 
     POSTAL_CODE VARCHAR (12) , 
     CITY VARCHAR (30)  NOT NULL , --!identity 
     STATE_PROVINCE VARCHAR (25) , --!identity 
     COUNTRY_ID CHAR (2) --!identity 
    ) 
;

ALTER TABLE HR.LOCATIONS ADD CONSTRAINT LOC_ID_PK PRIMARY KEY ( LOCATION_ID ) ;




/**Creacion de llaves foraneas**/

ALTER TABLE HR.LOCATIONS  ADD CONSTRAINT LOC_C_ID_FK  FOREIGN KEY (COUNTRY_ID) 
REFERENCES HR.COUNTRIES (COUNTRY_ID)
ALTER TABLE HR.COUNTRIES  ADD CONSTRAINT COUNTR_REG_FK FOREIGN KEY (REGION_ID) 
REFERENCES HR.REGIONS (REGION_ID)

ALTER TABLE HR.DEPARTMENTS ADD CONSTRAINT DEPT_LOC_FK FOREIGN KEY ( LOCATION_ID ) 
REFERENCES HR.LOCATIONS (LOCATION_ID)

ALTER TABLE HR.DEPARTMENTS ADD CONSTRAINT DEPT_MGR_FK FOREIGN KEY ( MANAGER_ID ) 
REFERENCES HR.EMPLOYEES (EMPLOYEE_ID) --!revisa

ALTER TABLE HR.EMPLOYEES ADD CONSTRAINT EMP_DEPT_FK FOREIGN KEY ( DEPARTMENT_ID ) 
REFERENCES HR.DEPARTMENTS (DEPARTMENT_ID) 

ALTER TABLE HR.EMPLOYEES ADD CONSTRAINT EMP_JOB_FK FOREIGN KEY (JOB_ID ) 
REFERENCES HR.JOBS  (JOB_ID) 

ALTER TABLE HR.EMPLOYEES ADD CONSTRAINT EMP_MANAGER_FK FOREIGN KEY (MANAGER_ID ) 
REFERENCES HR.EMPLOYEES  (EMPLOYEE_ID) --!revisa

ALTER TABLE HR.JOB_HISTORY ADD CONSTRAINT JHIST_DEPT_FK FOREIGN KEY (DEPARTMENT_ID ) 
REFERENCES HR.DEPARTMENTS   (DEPARTMENT_ID) --

ALTER TABLE HR.JOB_HISTORY  ADD CONSTRAINT JHIST_EMP_FK FOREIGN KEY (EMPLOYEE_ID ) 
REFERENCES HR.EMPLOYEES    (EMPLOYEE_ID) --!revisa
ALTER TABLE HR.JOB_HISTORY  ADD CONSTRAINT JHIST_JOB_FK FOREIGN KEY (JOB_ID ) 
REFERENCES HR.JOBS   (JOB_ID) 

/**drop table  HR.COUNTRIES,HR.DEPARTMENTS, HR.EMPLOYEES, HR.JOB_HISTORY, HR.JOBS, HR.LOCATIONS, HR.REGIONS**/